version: '3.2'

services:
    redis:
        image: "redis:7-alpine"
        ports:
        - "6379:6379"
        restart: unless-stopped
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
