# Generated by Django 5.2 on 2025-05-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0003_assessmentsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentsession',
            old_name='started_at',
            new_name='start_time',
        ),
    ]
