# Generated by Django 5.2 on 2025-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0005_alter_assessmentsession_start_time_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='groups', to='codingapp.assessment'),
        ),
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='groups', to='codingapp.module'),
        ),
    ]
