# Generated by Django 5.2 on 2025-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0006_group_assessments_group_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='group',
            name='modules',
        ),
        migrations.AddField(
            model_name='assessment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='codingapp.group'),
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='modules', to='codingapp.group'),
        ),
    ]
