# Generated by Django 5.2 on 2025-06-01 13:24

import codingapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(default=list, help_text="List of dicts with 'input' (string) and 'expected_output' (list of strings). Example: [{'input': '2', 'expected_output': ['2 2 2', '2 1 2', '2 2 2']}]", validators=[codingapp.models.validate_test_cases]),
        ),
    ]
