# Generated by Django 5.2 on 2025-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0009_alter_question_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='For MCQs: Correct option text', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='For MCQs: List of options', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('coding', 'Coding Problem'), ('mcq', 'Multiple Choice')], default='coding', max_length=20),
        ),
    ]
