# Generated by Django 5.2 on 2025-06-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0012_quizsubmission_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='codingapp.quiz'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='quiz_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
