# Generated by Django 5.2 on 2025-06-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0013_assessment_quiz_assessmentsession_quiz_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingapp.assessment'),
        ),
    ]
