# Generated by Django 5.2 on 2025-06-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0015_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codingapp.group'),
        ),
    ]
