# Generated by Django 5.2.7 on 2025-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0020_modulecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
