# Generated by Django 5.2.7 on 2025-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0021_assessmentsession_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_profile.png', null=True, upload_to='profiles/'),
        ),
    ]
