# Generated by Django 5.2.7 on 2025-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0022_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this module is visible to all students.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Assign this module to specific groups. Ignored if 'Is Public' is checked.", to='codingapp.group'),
        ),
    ]
