# Generated by Django 5.2.7 on 2025-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0023_actionpermission_userprofile_custom_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionpermission',
            options={'verbose_name': 'Action Permission', 'verbose_name_plural': 'Action Permissions'},
        ),
        migrations.AlterField(
            model_name='actionpermission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='actionpermission',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
