# Generated by Django 5.2.7 on 2025-11-04 21:32

import codingapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0024_alter_actionpermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(default=list, help_text="List of dicts with 'input' and 'expected_output' keys.", validators=[codingapp.models.validate_test_cases]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'question_type': 'mcq'}, to='codingapp.question'),
        ),
    ]
