# Generated by Django 5.2.7 on 2025-11-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0025_alter_group_students_alter_question_test_cases_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['department__name', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='codingapp.department'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'department')},
        ),
    ]
