# Generated by Django 5.2.7 on 2025-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0027_group_created_at_group_created_by_group_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this module is visible to all students.'),
        ),
    ]
