# Generated by Django 5.2.7 on 2025-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0028_module_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Assign this module to groups. Ignored if Is Public is enabled.', related_name='modules', to='codingapp.group'),
        ),
    ]
