# Generated by Django 5.2.7 on 2025-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0029_alter_module_options_alter_module_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
