# Generated by Django 5.2.7 on 2025-12-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0030_assessmentsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='warnings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
