# Generated by Django 5.2.7 on 2025-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0031_remove_assessmentsubmission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='plagiarism_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
