# Generated by Django 5.2.7 on 2025-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0032_assessmentsubmission_plagiarism_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='penalized_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='penalty_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='penalty_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='raw_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='raw_score',
            field=models.FloatField(blank=True, help_text='Raw marks before plagiarism penalty (0-5).', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
