# Generated by Django 5.2.7 on 2025-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0033_assessmentsession_penalized_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='ai_generated_prob',
            field=models.FloatField(blank=True, help_text='Estimated probability code is AI-generated (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='embedding_similarity',
            field=models.FloatField(blank=True, help_text='Embedding cosine similarity (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='fingerprint',
            field=models.TextField(blank=True, help_text='Optional fingerprint or hash for quick comparisons', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='structural_similarity',
            field=models.FloatField(blank=True, help_text='AST/structural similarity (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='token_similarity',
            field=models.FloatField(blank=True, help_text='Token/winnowing similarity (0.0-1.0)', null=True),
        ),
    ]
