# Generated by Django 5.2.7 on 2025-12-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0035_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
