# Generated by Django 5.2.7 on 2025-12-28 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0036_userprofile_leetcode_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_last_synced',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_username',
        ),
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforces_username', models.CharField(blank=True, max_length=100, null=True)),
                ('codeforces_stats', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
