# Generated by Django 5.2.7 on 2025-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0037_remove_userprofile_leetcode_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='leetcode_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='externalprofile',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
