# Generated by Django 5.2.7 on 2025-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0038_externalprofile_leetcode_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='codechef_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='externalprofile',
            name='codechef_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
