# Generated by Django 5.2.7 on 2025-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0039_externalprofile_codechef_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='hackerrank_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalprofile',
            name='hackerrank_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='externalprofile',
            name='hackerrank_verified',
            field=models.BooleanField(default=False),
        ),
    ]
