# Generated by Django 5.2.7 on 2025-12-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0040_externalprofile_hackerrank_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='hackerrank_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
